kind: Deployment
apiVersion: apps/v1
metadata:
  name: clamav-mirror
  namespace: cra
  labels:
    app: clamav-mirror
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav-mirror
  template:
    metadata:
      labels:
        app: clamav-mirror
    spec:
      volumes:
        - name: clamav
          persistentVolumeClaim:
            claimName: clamav
      containers:
        - name: clamav-mirror
          image: 'docker.io/levindecaro/clamav-mirror:v0.3'
          resources: {}
          volumeMounts:
            - name: clamav
              mountPath: /.cvdupdate
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: clamav-mirror-update
          command:
            - /bin/sh
          imagePullPolicy: Always
          volumeMounts:
            - name: clamav
              mountPath: /.cvdupdate
          terminationMessagePolicy: File
          image: 'docker.io/levindecaro/clamav-mirror:v0.3'
          args:
            - '-c'
            - while true;do cvdupdate update; sleep 14400;done
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
